logging:
  LOGGER_NAME: 'root'

load_data:

  SOURCE_BUCKET: "nw-srividyaganapathi-s3"
  local_location: "data/raw/mbti_1.csv"

db_config:
  SQLALCHEMY_DATABASE_URL: 'sqlite:///data/msia423_db.db'
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  SQLALCHEMY_ECHO: False  # If true, SQL for queries made will be printed



